// Generated by CoffeeScript 1.6.3
(function() {
  exports.config = {
    modules: ["minify-js", "minify-css", "jshint", "csslint", "live-reload", "bower", "server", "karma", "combine", "coffeelint", "just-copy"],
    watch: {
      javascriptDir: "js"
    },
    vendor: {
      javascripts: "js/vendor"
    },
    coffeescript: {
      sourceMap: true,
      bare: true
    },
    template: {
      wrapType: "none"
    },
    jshint: {
      exclude: [/(vendor|modernizr)/],
      vendor: false
    },
    csslint: {
      exclude: [/(vendor|modernizr)/]
    },
    bower: {
      watch: true,
      bowerDir: {
        path: ".mimosa/bower/bower_components",
        clean: true
      }
    },
    copy: {
      enabled: true,
      trackChanges: true,
      outRoot: null,
      exclude: [],
      unknownMainFullCopy: true,
      mainOverrides: {},
      strategy: "packageRoot",
      forceLatest: true,
      pathMod: []
    },
    server: {
      defaultServer: {
        enabled: false,
        onePager: false
      },
      path: 'server.coffee',
      packageJSONDir: null,
      port: 8000,
      base: '',
      views: {
        compileWith: 'html',
        extension: 'html',
        path: 'views'
      }
    },
    combine: {
      folders: [
        {
          folder: "javascripts/vendor/",
          output: "js/vendor.js",
          exclude: ["requirejs", "modernizr"],
          order: null
        }, {
          folder: "javascripts/app/",
          output: "js/app.js",
          exclude: null,
          order: null
        }
      ],
      removeCombined: {
        enabled: true,
        exclude: []
      }
    },
    coffeelint: {
      exclude: [],
      rules: {}
    },
    justCopy: {
      paths: ["javascripts/vendor/modernizr"]
    }
  };

}).call(this);
